updated .envexample to include new variables
rationally-app/mobile-application pull request #178
Opened 2020-09-13 14:48 UTC by glenda-wee

TEST_DOMAIN_CHECK, SENTRY_DSN and DOMAIN_CHECK

2020-09-13 15:41 UTC, dalsontws requested changes

2020-09-13 15:41 UTC, dalsontws commented on package.json
> +    "expo-updates": "~0.2.8",
oops, might have to update your `expo-updates` package to the latest version

2020-09-13 15:46 UTC, ilhaoni requested changes
Haha thanks for adding the example! Do you wanna add a short note into Readme to explain the vars as well? Also remember to remove the package.json updates haha

2020-09-16 01:16 UTC, ilhaoni reviewed
Reviewed~ some small changes to be made then ok le! ^^

2020-09-16 01:16 UTC, ilhaoni commented on README.md
> +TEST_DOMAIN_CHECK
We currently don't use this var, can remove haha

2020-09-16 01:16 UTC, ilhaoni commented on README.md
> +DOMAIN_CHECK: to validate backend endpoints
Haha should be `DOMAIN_FORMAT`

2020-09-24 07:53 UTC, ilhaoni approved these changes
LGTM! :D thanks for updating our Readme haha

2020-09-24 07:54 UTC, ilhaoni commented
@dalsontws need your review again! Haha ^^

2020-09-24 09:38 UTC, glenda-wee commented
> LGTM! :D thanks for updating our Readme haha

Thanks for helping me check through! :)

2020-09-24 09:39 UTC, glenda-wee commented
> LGTM! :D thanks for updating our Readme haha

Thanks for helping me look through it! :)

2020-09-24 09:44 UTC, dalsontws approved these changes
LGTM!🚢

2020-09-24 11:06 UTC, merged