Minor changes to dialog phrasing
rationally-app/mobile-application pull request #201
Opened 2020-09-24 10:42 UTC by glenda-wee

- Changed logout cancel button to 'No' instead of 'Cancel'. There were 'Cancel' buttons in the other dialog messages (e.g. 'Cancel entry' when users scan a wrong ID). The change to 'No' prevents users from getting mixed up between all the cancel buttons throughout the app. 

- Added 'a' to some phrases to maintain consistency with the English for the rest of the dialog messages.

- Removed the word 'details' to maintain consistency with the Chinese translations.

2020-09-24 15:19 UTC, dalsontws requested changes

2020-09-24 15:19 UTC, dalsontws commented on src/context/alert.tsx
> +  INVALID_PHONE_AND_COUNTRY_CODE = "Enter a valid country code and contact number.",
for the changes in the error messages here, would have to make the same changes to the relevant test cases too!

2020-09-27 16:11 UTC, dalsontws approved these changes
Nice! LGTM!🚢

2020-09-28 11:57 UTC, glenda-wee commented
Thanks Dalson! Will merge now :)

2020-09-28 11:58 UTC, merged