feat: use label in accessibilityLabel for IdentifierTextInput
rationally-app/mobile-application pull request #324
Opened 2021-03-16 04:55 UTC by ilhaoni

This allows us to differentiate each identifierInput, as each of them will have a unique accessibilityLabel. Currently they all have the same label of `item-field-text`

[Notion link](notion-link-here) 

This PR adds... 

- [ ] I've kept this PR as small as possible (~600 lines) by splitting it into PRs with manageable chunks of code
- [ ] I've requested reviews from 1-2 reviewers
- [ ] I've added [accessibility IDs](https://www.notion.so/dc5f4ce910f7431c84344ac79344e9f5?v=d487366816834dd4ab8dc12e0b5928f3) to my components
- [ ] I've added/updated unit/integration tests
- [ ] I've added/updated [e2e tests](https://www.notion.so/e2e-Documentation-a096d3e0bf75485e85ad692af8371ef3) for at least the happy flow
- [ ] I've added [Chinese translations for i18n setup](https://www.notion.so/Translations-Dev-Guide-8c1da838982a4f59a386ec96ac6780c8)
- [ ] I've added documentation in README/[Notion](https://www.notion.so/82b92fb1007640328dab9582c0a3694e?v=3b6ce48202cf40ad8450553799b13146)

2021-03-22 06:49 UTC, yongjiajie reviewed
Looks good! Would it make sense to extract this logic into a utility function we can use in the future? Or do we forsee not using this a lot?

2021-03-22 09:37 UTC, andrehadianto requested changes
should we add `testId` as well? Since the document mentioned that `testId` is used for iOS while `accessibilityLabel` is used for Android

2021-03-23 02:42 UTC, ilhaoni commented
Hmm @yongjiajie currently we know for sure that identifiers have labels, so I was thinking we can push this first, and then we examine how to create a utility function 🤔  what do you think about this haha. Feels very trial and error at the moment 😂 

So far, only identifiers seem to have the same accessibility ids [here](https://www.notion.so/Testing-Add-essential-accessibility-IDs-3c0fd1ebab2041a5b0312664b7299000). I guess the next ones to tackle will be 
- logout related 
- distribution name
- stepper related
- checkbox related

@andrehadianto ahh, it does pass down to `testId`! 
- `IdentifierPhoneNumberInput` uses `PhoneNumberInput`, which generates all the `accessibilityLabel` for Android and `testID` for iOS haha
-  `IdentifierTextInput` uses `InputWithLabel`, which generates all the `accessibilityLabel` for Android and `testID` for iOS haha

2021-03-23 05:30 UTC, yongjiajie approved these changes
Sounds good, I thought it was something consistent! Thanks for sharing the context 🎉

2021-03-24 02:27 UTC, andrehadianto approved these changes

2021-03-24 02:30 UTC, merged