feat(tech debt): FE components testing
rationally-app/mobile-application pull request #325
Opened 2021-03-19 08:23 UTC by andrehadianto

[Notion link](https://www.notion.so/Frontend-2dcbb8ad3f234aee98d5f289d3170b40#f01038cb652e426fa36ce23b38238fa8) 

This PR adds... 
- Component testing using @testing-library/react-native
- Unit tests for `LoginMobileNumberCard`, `LoginOTPCard`, and `LoginScanCard`

- [ ] I've kept this PR as small as possible (~600 lines) by splitting it into PRs with manageable chunks of code
- [ ] I've requested reviews from 1-2 reviewers
- [ ] I've added [accessibility IDs](https://www.notion.so/dc5f4ce910f7431c84344ac79344e9f5?v=d487366816834dd4ab8dc12e0b5928f3) to my components
- [ ] I've added/updated unit/integration tests
- [ ] I've added/updated [e2e tests](https://www.notion.so/e2e-Documentation-a096d3e0bf75485e85ad692af8371ef3) for at least the happy flow
- [ ] I've added [Chinese translations for i18n setup](https://www.notion.so/Translations-Dev-Guide-8c1da838982a4f59a386ec96ac6780c8)
- [ ] I've added documentation in README/[Notion](https://www.notion.so/82b92fb1007640328dab9582c0a3694e?v=3b6ce48202cf40ad8450553799b13146)

2021-03-23 10:28 UTC, maksha19 requested changes

2021-03-23 10:28 UTC, maksha19 commented on src/components/Login/LoginMobileNumberCard.test.tsx
> +    const submitButton = getByTestId("login-send-otp-button");
can move the testId `login-phone-number-input` and  `login-send-otp-button` to const variable.. easy to maintain at one place

2021-03-23 10:28 UTC, maksha19 commented on src/components/Login/LoginMobileNumberCard.test.tsx
> +      expect(queryByText("Enter a valid contact number.")).not.toBeNull();
can move to const variable `Enter a valid contact number.`

2021-03-23 10:28 UTC, maksha19 commented on src/components/Login/LoginMobileNumberCard.test.tsx
> +      const submitButton = getByTestId("login-send-otp-button");
can re-use the const variable from line 40,41

2021-03-23 10:28 UTC, maksha19 commented on src/components/Login/LoginMobileNumberCard.test.tsx
> +      const submitButton = getByTestId("login-send-otp-button");
can re-use the const variable from line 40,41

2021-03-23 10:28 UTC, maksha19 commented on src/components/Login/LoginMobileNumberCard.test.tsx
> +      expect(queryByText("Enter a valid contact number.")).not.toBeNull();
can re-use the const variable from line 79

2021-03-23 10:28 UTC, maksha19 commented on src/components/Login/LoginOTPCard.test.tsx
> +    const submitButton = getByTestId("login-submit-otp-button");
can change the TestId string  to const variable

2021-03-23 10:28 UTC, maksha19 commented on src/components/Login/LoginOTPCard.test.tsx
> +      const submitButton = getByTestId("login-submit-otp-button");
can re-use the const variable from line 57,58

2021-03-23 10:28 UTC, maksha19 commented on src/components/Login/LoginOTPCard.test.tsx
> +      const submitButton = getByTestId("login-submit-otp-button");
can re-use the const variable from line 57,58

2021-03-23 10:28 UTC, maksha19 commented on src/components/Login/LoginOTPCard.test.tsx
> +      const submitButton = getByTestId("login-submit-otp-button");
can re-use the const variable from line 57,58

2021-03-23 10:28 UTC, maksha19 commented on src/components/Login/LoginOTPCard.test.tsx
> +      const submitButton = getByTestId("login-submit-otp-button");
can re-use the const variable from line 58

2021-03-23 10:28 UTC, maksha19 commented on src/components/Login/LoginOTPCard.test.tsx
> +      const submitButton = getByTestId("login-submit-otp-button");
can re-use the const variable from line 57,58

2021-03-24 07:15 UTC, sebastianquek reviewed
Good job @andrehadianto ! Just a couple of comments!

2021-03-24 07:15 UTC, sebastianquek commented on src/components/Login/LoginScanCard.test.tsx
> +    expect.hasAssertions();
We've been specifying the actual number of assertions so we make sure that all assertions are being asserted

2021-03-24 07:15 UTC, sebastianquek commented on src/components/Login/LoginMobileNumberCard.test.tsx
> +  it("should be able to fetch the endpoint without error", async () => {
This test name is not very descriptive, perhaps you can express what the test is trying to assert.
e.g. "should request for OTP successfully on pressing submit"

2021-03-24 07:15 UTC, sebastianquek commented on src/components/Login/LoginOTPCard.test.tsx
> +const fullPhoneNumber = "6588888888";
This looks like a malformed number since it doesn't include the '+'

2021-03-24 07:15 UTC, sebastianquek commented on src/components/Login/LoginOTPCard.test.tsx
> +  it("should be able to fetch the endpoint without error", async () => {
This test description can be more specific too!

2021-03-31 02:26 UTC, maksha19 approved these changes
LGTM 🚀

2021-03-31 02:38 UTC, merged