Feat/payment sequence flow
rationally-app/mobile-application pull request #385
Opened 2021-07-02 07:43 UTC by andrehadianto

[Notion link](https://www.notion.so/Sequence-of-flow-for-Payment-collected-dialog-box-and-error-dialog-box-6702ba3744e84ab3b99153e5914326cc) 

This PR adds... 
- separate checkoutConfirmation and add PENDING_CONFIRMATION state
- add useEffect in `ItemsSelectionCard` to check whether cartState is `PENDING_CONFIRMATION`

- [ ] I've kept this PR as small as possible (~600 lines) by splitting it into PRs with manageable chunks of code
- [ ] I've requested reviews from 1-2 reviewers
- [ ] I've added [accessibility IDs](https://www.notion.so/dc5f4ce910f7431c84344ac79344e9f5?v=d487366816834dd4ab8dc12e0b5928f3) to my components
- [ ] I've added/updated unit/integration tests
- [ ] I've added/updated [e2e tests](https://www.notion.so/e2e-Documentation-a096d3e0bf75485e85ad692af8371ef3) for at least the happy flow
- [ ] I've added [Chinese translations for i18n setup](https://www.notion.so/Translations-Dev-Guide-8c1da838982a4f59a386ec96ac6780c8)
- [ ] I've added documentation in README/[Notion](https://www.notion.so/82b92fb1007640328dab9582c0a3694e?v=3b6ce48202cf40ad8450553799b13146)

2021-07-08 06:53 UTC, sebastianquek commented on src/hooks/useCart/useCart.tsx
>     * Sets checkoutResult to the response of the post transaction.
Please add a comment on the purpose of this function too!

2021-07-08 06:53 UTC, sebastianquek commented on src/hooks/useCart/useCart.tsx
> +   * Handles the checking out of the cart.
Will be good to add that if there's a need to confirm payment, then the other `completeCheckout` must be called

2021-07-08 06:53 UTC, sebastianquek commented on src/hooks/useCart/useCart.test.tsx
> +    it("should show PENDING_CONFIRMATION cart state when a PAYMENT_RECEIPT identifier input exists", async () => {
Would be good to have a test that calls the completeCheckout as well

2021-07-08 16:22 UTC, sebastianquek commented on src/hooks/useCart/useCart.test.tsx
> +    it("should be able to complete a transaction without going through checkoutCart", async () => {
Hmm come to think of it ah, it'll be better if we restrict it such that the state must be "PENDING_CONFIRMATION" when `completeCheckout` is called. This ensures `checkoutCart`, with all its validations, have already been carried out

2021-07-14 06:47 UTC, yongjiajie requested changes

2021-07-14 06:47 UTC, yongjiajie commented on src/components/CustomerQuota/ItemsSelection/ItemsSelectionCard.tsx
>    // TODO:
Was this check for `alert` moved somewhere else?

2021-07-14 13:01 UTC, sebastianquek commented on src/hooks/useCart/useCart.tsx
> +  const closeCheckoutCart = useCallback(() => {
Hmm "close" is a little strange in the context. Perhaps we can keep it simple with `_completeCheckout`? The underscore indicates it's an internal function

2021-07-16 10:13 UTC, sebastianquek approved these changes
LGTM!!

2021-07-19 02:25 UTC, yongjiajie approved these changes
LGTM

2021-07-19 02:25 UTC, merged